import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { catchError, shareReplay } from 'rxjs/operators';

export interface BuildInfo {
  /** Output of `git describe --tags --always --dirty` at build time. */
  version: string;
  /** ISO timestamp captured when the frontend was built, or null if unknown (e.g. dev server). */
  buildTime: string | null;
}

const UNKNOWN_BUILD_INFO: BuildInfo = { version: 'unknown', buildTime: null };

/**
 * Reads assets/build-info.json, generated by generate-version.js as part of
 * `npm run build`. Lets the UI show which build is actually running, so a dev
 * reloading after a rebuild can tell it's not a stale cached bundle.
 */
@Injectable({
  providedIn: 'root'
})
export class BuildInfoService {

  private buildInfo$: Observable<BuildInfo> | null = null;

  constructor(private httpClient: HttpClient) { }

  public getBuildInfo(): Observable<BuildInfo> {
    if (!this.buildInfo$) {
      this.buildInfo$ = this.httpClient.get<BuildInfo>('assets/build-info.json').pipe(
        catchError(() => of(UNKNOWN_BUILD_INFO)),
        shareReplay(1)
      );
    }
    return this.buildInfo$;
  }
}
